emit upgrade event with db
lrlna/nanoidb pull request #2
Opened 2017-05-18 15:55 UTC by axelav

allows testing against a db's previous version to upgrade schemas

2017-05-18 16:35 UTC, lrlna requested changes
Awesome catch! Thank you :sparkles:

Would you mind doing a quick rebase with master and maybe making a change in `example.js` to use the object to `db.createObjectStore()` ?

2017-05-18 16:35 UTC, lrlna commented on README.md
> +calling `db.createObjectStore('<name>')`.
this should then be `indexedDB.db.createObjectStore('<name>')` ( i didn't quite have it right the first time either hah

2017-05-18 19:11 UTC, axelav commented
cool! yes, I will take care of those changes.

2017-05-20 22:12 UTC, axelav commented
ok all set. I think I hit all the spots that needed to be changed in the docs. wasn't really sure what to call that object that's returned - certainly not tied to `upgradeData` if you have a better suggestion.

2017-05-25 00:20 UTC, lrlna approved these changes

2017-05-25 00:32 UTC, merged

2017-05-25 00:33 UTC, lrlna commented
yay!! I got it in `v1.1.0` 📦 

Thanks so much ^___^